# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/liberal-boy/tls-shunt-proxy
%global goipath         github.com/liberal-boy/tls-shunt-proxy
Version:                0.6.1
%global tag             0.6.1

%gometa

%global common_description %{expand:
分流 TLS 流量，支持按 sni 分流，分流 http 和无特征流量.}

%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        分流 TLS 流量，支持按 sni 分流，分流 http 和无特征流量

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/caddyserver/certmagic)
BuildRequires:  golang(github.com/go-acme/lego/v3/challenge/tlsalpn01)
BuildRequires:  golang(github.com/stevenjohnstone/sni)
BuildRequires:  golang(golang.org/x/net/http2)
BuildRequires:  golang(golang.org/x/net/http2/h2c)
BuildRequires:  golang(gopkg.in/yaml.v2)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/tls-shunt-proxy %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%doc %{godocs}
%{_bindir}/*

%gopkgfiles

%changelog
* Sat Nov 21 2020 sixg0000d <sixg0000d@gmail.com> - 0.6.1-1
- Initial package

